// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV8RPbk1bqWW4v6mg4skMZsv6PP52mxo4',
    appId: '1:532912094954:web:68e702f1e91ba428bfa193',
    messagingSenderId: '532912094954',
    projectId: 'myprojectfirebase-a4a36',
    authDomain: 'myprojectfirebase-a4a36.firebaseapp.com',
    storageBucket: 'myprojectfirebase-a4a36.firebasestorage.app',
    measurementId: 'G-8LBD6P2Y5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtRlX55IZKQ5hc3Yzdz9W2VO2Sw8Uc_LM',
    appId: '1:532912094954:android:757705873e248f43bfa193',
    messagingSenderId: '532912094954',
    projectId: 'myprojectfirebase-a4a36',
    storageBucket: 'myprojectfirebase-a4a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUmYrff1P2ePRTys_i-8-PRT96t5n10U',
    appId: '1:532912094954:ios:740e0c69d7c0ad76bfa193',
    messagingSenderId: '532912094954',
    projectId: 'myprojectfirebase-a4a36',
    storageBucket: 'myprojectfirebase-a4a36.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTorTor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUmYrff1P2ePRTys_i-8-PRT96t5n10U',
    appId: '1:532912094954:ios:740e0c69d7c0ad76bfa193',
    messagingSenderId: '532912094954',
    projectId: 'myprojectfirebase-a4a36',
    storageBucket: 'myprojectfirebase-a4a36.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTorTor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV8RPbk1bqWW4v6mg4skMZsv6PP52mxo4',
    appId: '1:532912094954:web:deeebabbcb76c911bfa193',
    messagingSenderId: '532912094954',
    projectId: 'myprojectfirebase-a4a36',
    authDomain: 'myprojectfirebase-a4a36.firebaseapp.com',
    storageBucket: 'myprojectfirebase-a4a36.firebasestorage.app',
    measurementId: 'G-HVBLCB6BYN',
  );

}